openapi: 3.0.3
info:
  title: Shan Game APIs
  description: |
    Complete API documentation for Shan Game platform including balance management, 
    game launching, transaction processing, and callback handling.
    
    ## Features
    - Player balance management
    - Game launching and integration
    - Transaction processing
    - Real-time callback handling
    - Signature-based authentication
    
    ## Authentication
    - Bearer Token for player endpoints
    - MD5 Signature for provider callbacks
    - API Key authentication for some endpoints
  version: 1.0.0
  contact:
    name: API Support
    email: api-support@your-domain.com
    url: https://docs.your-domain.com
  license:
    name: Proprietary
    url: https://your-domain.com/license

servers:
  - url: https://your-domain.com/api
    description: Production server
  - url: https://staging.your-domain.com/api
    description: Staging server

security:
  - BearerAuth: []
  - SignatureAuth: []

paths:
  /login:
    post:
      summary: User Authentication
      description: Authenticate user and get bearer token
      tags:
        - Authentication
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_name
                - password
              properties:
                user_name:
                  type: string
                  example: "PLAYER001"
                password:
                  type: string
                  example: "password123"
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  token:
                    type: string
                    example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9..."
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      user_name:
                        type: string
                      name:
                        type: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /shan/balance:
    post:
      summary: Get Player Balance (Shan)
      description: Retrieve player balance information for Shan games
      tags:
        - Balance Management
      security:
        - SignatureAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShanBalanceRequest'
            examples:
              single_player:
                summary: Single player balance request
                value:
                  batch_requests:
                    - member_account: "PLAYER001"
                      product_code: 1002
                  operator_code: "SCT931"
                  currency: "MMK"
                  sign: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
                  request_time: 1640995200
      responses:
        '200':
          description: Balance retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShanBalanceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/InvalidSignature'

  /shan/shangetbalance:
    post:
      summary: Shankomee Get Balance
      description: Get balance information for Shankomee integration
      tags:
        - Balance Management
      security:
        - SignatureAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShankomeeBalanceRequest'
      responses:
        '200':
          description: Balance retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShankomeeBalanceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/InvalidSignature'

  /shankomee/launch-game:
    post:
      summary: Launch Shan Game
      description: Launch a Shan game for an authenticated player
      tags:
        - Game Management
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LaunchGameRequest'
      responses:
        '200':
          description: Game launched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchGameResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/ValidationError'

  /transactions:
    post:
      summary: Create Game Transaction
      description: Create a new game transaction with player and banker data
      tags:
        - Transaction Management
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionRequest'
      responses:
        '200':
          description: Transaction created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTransactionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/DuplicateTransaction'
        '422':
          $ref: '#/components/responses/ValidationError'

  /shan/client/balance-update:
    post:
      summary: Balance Update Callback
      description: Handle balance updates from the game provider
      tags:
        - Callbacks
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BalanceUpdateCallbackRequest'
      responses:
        '200':
          description: Balance updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceUpdateCallbackResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from login endpoint
    SignatureAuth:
      type: apiKey
      in: header
      name: X-Signature
      description: MD5 signature for authentication

  schemas:
    ShanBalanceRequest:
      type: object
      required:
        - batch_requests
        - operator_code
        - currency
        - sign
        - request_time
      properties:
        batch_requests:
          type: array
          items:
            type: object
            required:
              - member_account
              - product_code
            properties:
              member_account:
                type: string
                example: "PLAYER001"
              product_code:
                type: integer
                example: 1002
        operator_code:
          type: string
          example: "SCT931"
        currency:
          type: string
          example: "MMK"
        sign:
          type: string
          example: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
        request_time:
          type: integer
          example: 1640995200

    ShanBalanceResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        data:
          type: array
          items:
            type: object
            properties:
              member_account:
                type: string
                example: "PLAYER001"
              product_code:
                type: integer
                example: 1002
              balance:
                type: number
                example: 1500.50
              code:
                type: integer
                example: 0
              message:
                type: string
                example: "Success"

    ShankomeeBalanceRequest:
      type: object
      required:
        - batch_requests
        - operator_code
        - currency
        - request_time
        - sign
      properties:
        batch_requests:
          type: array
          items:
            type: object
            required:
              - member_account
              - product_code
              - balance
            properties:
              member_account:
                type: string
                example: "PLAYER001"
              product_code:
                type: integer
                example: 1002
              balance:
                type: number
                example: 1500.50
        operator_code:
          type: string
          example: "SCT931"
        currency:
          type: string
          example: "MMK"
        request_time:
          type: integer
          example: 1640995200
        sign:
          type: string
          example: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"

    ShankomeeBalanceResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        data:
          type: array
          items:
            type: object
            properties:
              member_account:
                type: string
                example: "PLAYER001"
              product_code:
                type: integer
                example: 1002
              balance:
                type: number
                example: 1500.50
              currency:
                type: string
                example: "MMK"
              status:
                type: string
                example: "success"

    LaunchGameRequest:
      type: object
      required:
        - product_code
        - game_type
      properties:
        product_code:
          type: integer
          example: 1002
        game_type:
          type: string
          example: "slot"
        nickname:
          type: string
          example: "PlayerNick"

    LaunchGameResponse:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
          example: "Game launched successfully"
        url:
          type: string
          example: "https://goldendragon7.pro/?user_name=PLAYER001&balance=1500.50"

    CreateTransactionRequest:
      type: object
      required:
        - banker
        - players
      properties:
        banker:
          type: object
          required:
            - player_id
          properties:
            player_id:
              type: string
              example: "BANKER001"
        players:
          type: array
          items:
            type: object
            required:
              - player_id
              - bet_amount
              - win_lose_status
            properties:
              player_id:
                type: string
                example: "PLAYER001"
              bet_amount:
                type: number
                minimum: 0
                example: 100.00
              win_lose_status:
                type: integer
                enum: [0, 1]
                example: 1

    CreateTransactionResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        message:
          type: string
          example: "Transaction Successful"
        data:
          type: array
          items:
            type: object
            properties:
              player_id:
                type: string
                example: "PLAYER001"
              balance:
                type: number
                example: 1100.00

    BalanceUpdateCallbackRequest:
      type: object
      required:
        - wager_code
        - players
        - timestamp
      properties:
        wager_code:
          type: string
          example: "hl1pIjmevmVU"
        game_type_id:
          type: integer
          example: 15
        players:
          type: array
          items:
            type: object
            required:
              - player_id
              - balance
            properties:
              player_id:
                type: string
                example: "PLAYER001"
              balance:
                type: number
                example: 1200.75
        banker_balance:
          type: number
          example: 50000.00
        timestamp:
          type: string
          format: date-time
          example: "2025-01-15T10:30:00Z"
        total_player_net:
          type: number
          example: -299.25
        banker_amount_change:
          type: number
          example: 299.25

    BalanceUpdateCallbackResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        code:
          type: string
          example: "SUCCESS"
        message:
          type: string
          example: "Balances updated successfully."

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: "error"
        code:
          type: string
          example: "ERROR_CODE"
        message:
          type: string
          example: "Error description"
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          example:
            field_name: ["Validation error message"]

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized - Invalid or missing authentication
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InvalidSignature:
      description: Invalid signature
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    ValidationError:
      description: Validation Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    DuplicateTransaction:
      description: Duplicate transaction
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

tags:
  - name: Authentication
    description: User authentication and token management
  - name: Balance Management
    description: Player balance retrieval and management
  - name: Game Management
    description: Game launching and integration
  - name: Transaction Management
    description: Game transaction processing
  - name: Callbacks
    description: Provider callback handling
